apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events-app-dev
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # I was not able to make this work... so SHA256
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - .spec.template.spec.initContainers[*].image
  #   - .spec.template.spec.containers[*].image
  destination:
    namespace: gramola-dev
    name: {{ .Values.destinationName }}
  project: gramola-project-dev
  syncPolicy:
    automated:
      selfHeal: true
  source:
    # This is not possible because plugin has been set to kustomized-helm and source.helm applies only to helm
    # helm:
    #   parameters:
    #     - name: clusterName
    #       value: {{ .Values.destinationName }}
    path: events-deployment/overlays/dev
    repoURL: "{{ .Values.gitUrl }}/{{ .Values.gitUsername }}/{{ .Values.baseRepoName }}.git"
    targetRevision: {{ .Values.gitRevision }}
    plugin:
      env:
        - name: DESTINATION_NAME
          value: "{{ .Values.destinationName }}"
        - name: GIT_URL
          value: "{{ .Values.gitUrl }}"
        - name: GIT_USERNAME
          value: "{{ .Values.gitUsername }}"
        - name: BASE_REPO_NAME
          value: "{{ .Values.baseRepoName }}"
        - name: GIT_REVISION
          value: "{{ .Values.gitRevision }}"
      name: kustomized-helm