apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-app-test-cloud
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gramola-test
    name: {{ .Values.destinationName }}
  project: gramola-project-test
  syncPolicy:
    automated:
      selfHeal: true
  source:
    # This is not possible because plugin has been set to kustomized-helm and source.helm applies only to helm
    # helm:
    #   parameters:
    #     - name: clusterName
    #       value: {{ .Values.destinationName }}
    path: gateway-deployment/overlays/test-cloud
    repoURL: "{{ .Values.gitUrl }}/{{ .Values.gitUsername }}/{{ .Values.baseRepoName }}.git"
    targetRevision: {{ .Values.gitRevision }}
    plugin:
      env:
        - name: DESTINATION_NAME
          value: "{{ .Values.destinationName }}"
        - name: GIT_URL
          value: "{{ .Values.gitUrl }}"
        - name: GIT_USERNAME
          value: "{{ .Values.gitUsername }}"
        - name: BASE_REPO_NAME
          value: "{{ .Values.baseRepoName }}"
        - name: GIT_REVISION
          value: "{{ .Values.gitRevision }}"
      name: kustomized-helm